name: shurjopay
description: Official shurjoPay flutter package for merchants or service providers to integrate our payment system with their Flutter applications.
version: 2.0.3
homepage: https://shurjomukhi.com.bd

environment:
  sdk: ">=2.18.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0
  get_it: ^7.6.7
  webview_flutter: ^4.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
