name: shurjopay
description: Official shurjoPay Flutter package for merchants or service providers to integrate our payment system with their Flutter applications.
version: 2.0.4
homepage: https://shurjomukhi.com.bd

environment:
  sdk: '>=2.18.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.6
  get_it: ^7.6.7
  webview_flutter: ^2.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: